# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waitingroom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11waitingroom.proto\x12\x0bwaitingroom\"M\n\x16\x45nqueueCustomerRequest\x12\x0e\n\x06ipaddr\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t\x12\x10\n\x08phonenum\x18\x03 \x01(\t\"&\n\x14\x45nqueueCustomerReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"G\n\x10WaitQueueRequest\x12\x0e\n\x06ipaddr\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t\x12\x10\n\x08phonenum\x18\x03 \x01(\t\"s\n\x0eWaitQueueReply\x12\x0e\n\x06ipaddr\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t\x12\x10\n\x08phonenum\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\x12\x10\n\x08selected\x18\x06 \x01(\x08\"\x18\n\x16\x44\x65queueCustomerRequest\"l\n\x14\x44\x65queueCustomerReply\x12\x0e\n\x06ipaddr\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t\x12\x10\n\x08phonenum\x18\x03 \x01(\t\x12\x0e\n\x06inTime\x18\x04 \x01(\t\x12\x0f\n\x07outTime\x18\x05 \x01(\t\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"6\n\x12ValidateTokenReply\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tvalidated\x18\x02 \x01(\t2\xb7\x01\n\x0bWaitingRoom\x12[\n\x0f\x45nqueueCustomer\x12#.waitingroom.EnqueueCustomerRequest\x1a!.waitingroom.EnqueueCustomerReply\"\x00\x12K\n\tWaitQueue\x12\x1d.waitingroom.WaitQueueRequest\x1a\x1b.waitingroom.WaitQueueReply\"\x00\x30\x01\x32\xce\x01\n\x07\x44\x65queue\x12\x61\n\x15\x44\x65queueRandomCustomer\x12#.waitingroom.DequeueCustomerRequest\x1a!.waitingroom.DequeueCustomerReply\"\x00\x12`\n\x14\x44\x65queueFirstCustomer\x12#.waitingroom.DequeueCustomerRequest\x1a!.waitingroom.DequeueCustomerReply\"\x00\x32\x62\n\tValidator\x12U\n\rValidateToken\x12!.waitingroom.ValidateTokenRequest\x1a\x1f.waitingroom.ValidateTokenReply\"\x00\x62\x06proto3')



_ENQUEUECUSTOMERREQUEST = DESCRIPTOR.message_types_by_name['EnqueueCustomerRequest']
_ENQUEUECUSTOMERREPLY = DESCRIPTOR.message_types_by_name['EnqueueCustomerReply']
_WAITQUEUEREQUEST = DESCRIPTOR.message_types_by_name['WaitQueueRequest']
_WAITQUEUEREPLY = DESCRIPTOR.message_types_by_name['WaitQueueReply']
_DEQUEUECUSTOMERREQUEST = DESCRIPTOR.message_types_by_name['DequeueCustomerRequest']
_DEQUEUECUSTOMERREPLY = DESCRIPTOR.message_types_by_name['DequeueCustomerReply']
_VALIDATETOKENREQUEST = DESCRIPTOR.message_types_by_name['ValidateTokenRequest']
_VALIDATETOKENREPLY = DESCRIPTOR.message_types_by_name['ValidateTokenReply']
EnqueueCustomerRequest = _reflection.GeneratedProtocolMessageType('EnqueueCustomerRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENQUEUECUSTOMERREQUEST,
  '__module__' : 'waitingroom_pb2'
  # @@protoc_insertion_point(class_scope:waitingroom.EnqueueCustomerRequest)
  })
_sym_db.RegisterMessage(EnqueueCustomerRequest)

EnqueueCustomerReply = _reflection.GeneratedProtocolMessageType('EnqueueCustomerReply', (_message.Message,), {
  'DESCRIPTOR' : _ENQUEUECUSTOMERREPLY,
  '__module__' : 'waitingroom_pb2'
  # @@protoc_insertion_point(class_scope:waitingroom.EnqueueCustomerReply)
  })
_sym_db.RegisterMessage(EnqueueCustomerReply)

WaitQueueRequest = _reflection.GeneratedProtocolMessageType('WaitQueueRequest', (_message.Message,), {
  'DESCRIPTOR' : _WAITQUEUEREQUEST,
  '__module__' : 'waitingroom_pb2'
  # @@protoc_insertion_point(class_scope:waitingroom.WaitQueueRequest)
  })
_sym_db.RegisterMessage(WaitQueueRequest)

WaitQueueReply = _reflection.GeneratedProtocolMessageType('WaitQueueReply', (_message.Message,), {
  'DESCRIPTOR' : _WAITQUEUEREPLY,
  '__module__' : 'waitingroom_pb2'
  # @@protoc_insertion_point(class_scope:waitingroom.WaitQueueReply)
  })
_sym_db.RegisterMessage(WaitQueueReply)

DequeueCustomerRequest = _reflection.GeneratedProtocolMessageType('DequeueCustomerRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEQUEUECUSTOMERREQUEST,
  '__module__' : 'waitingroom_pb2'
  # @@protoc_insertion_point(class_scope:waitingroom.DequeueCustomerRequest)
  })
_sym_db.RegisterMessage(DequeueCustomerRequest)

DequeueCustomerReply = _reflection.GeneratedProtocolMessageType('DequeueCustomerReply', (_message.Message,), {
  'DESCRIPTOR' : _DEQUEUECUSTOMERREPLY,
  '__module__' : 'waitingroom_pb2'
  # @@protoc_insertion_point(class_scope:waitingroom.DequeueCustomerReply)
  })
_sym_db.RegisterMessage(DequeueCustomerReply)

ValidateTokenRequest = _reflection.GeneratedProtocolMessageType('ValidateTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATETOKENREQUEST,
  '__module__' : 'waitingroom_pb2'
  # @@protoc_insertion_point(class_scope:waitingroom.ValidateTokenRequest)
  })
_sym_db.RegisterMessage(ValidateTokenRequest)

ValidateTokenReply = _reflection.GeneratedProtocolMessageType('ValidateTokenReply', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATETOKENREPLY,
  '__module__' : 'waitingroom_pb2'
  # @@protoc_insertion_point(class_scope:waitingroom.ValidateTokenReply)
  })
_sym_db.RegisterMessage(ValidateTokenReply)

_WAITINGROOM = DESCRIPTOR.services_by_name['WaitingRoom']
_DEQUEUE = DESCRIPTOR.services_by_name['Dequeue']
_VALIDATOR = DESCRIPTOR.services_by_name['Validator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENQUEUECUSTOMERREQUEST._serialized_start=34
  _ENQUEUECUSTOMERREQUEST._serialized_end=111
  _ENQUEUECUSTOMERREPLY._serialized_start=113
  _ENQUEUECUSTOMERREPLY._serialized_end=151
  _WAITQUEUEREQUEST._serialized_start=153
  _WAITQUEUEREQUEST._serialized_end=224
  _WAITQUEUEREPLY._serialized_start=226
  _WAITQUEUEREPLY._serialized_end=341
  _DEQUEUECUSTOMERREQUEST._serialized_start=343
  _DEQUEUECUSTOMERREQUEST._serialized_end=367
  _DEQUEUECUSTOMERREPLY._serialized_start=369
  _DEQUEUECUSTOMERREPLY._serialized_end=477
  _VALIDATETOKENREQUEST._serialized_start=479
  _VALIDATETOKENREQUEST._serialized_end=516
  _VALIDATETOKENREPLY._serialized_start=518
  _VALIDATETOKENREPLY._serialized_end=572
  _WAITINGROOM._serialized_start=575
  _WAITINGROOM._serialized_end=758
  _DEQUEUE._serialized_start=761
  _DEQUEUE._serialized_end=967
  _VALIDATOR._serialized_start=969
  _VALIDATOR._serialized_end=1067
# @@protoc_insertion_point(module_scope)
