apiVersion: v1
kind: Service
metadata:
  name: queue-server-headless-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: queue-server
  ports:
    - protocol: TCP
      port: 5051
      targetPort: 5051
