apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: queue-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: queue-server
  minReplicas: 1
  maxReplicas: 6
  # targetCPUUtilizationPercentage: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
