apiVersion: v1
kind: Service
metadata:
  name: queue-server-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: queue-server
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345