apiVersion: v1
kind: Service
metadata:
  labels:
    app: queue-server
  name: queue-server-nodeport-service
spec:
  type: NodePort
  selector:
    app: queue-server
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
      nodePort: 32003
