version: '3'
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: useradmin
      MONGO_INITDB_ROOT_PASSWORD: csc3004
  
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: useradmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: csc3004
      ME_CONFIG_MONGODB_SERVER: mongo