apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongoexpress-nodeport-service
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 32002
