apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          image: mongo
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "rs0"
          ports:
            - containerPort: 27017
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          env:
            # - name: MONGO_INITDB_ROOT_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-creds
            #       key: username
            # - name: MONGO_INITDB_ROOT_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-creds
            #       key: password
          volumeMounts:
            - name: mongo-data-dir
              mountPath: /data/db
        - name: mongo-sidecar
          image: yxchia98/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "app=mongo"
            # - name: MONGODB_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-creds
            #       key: username
            # - name: MONGODB_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-creds
            #       key: password
      serviceAccountName: admin
  volumeClaimTemplates:
    - metadata:
        name: mongo-data-dir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
