apiVersion: v1
kind: Secret
data:
  username: YWRtaW51c2Vy #adminuser
  password: Y3NjMzAwNA== #csc3004
  db_access: bW9uZ29kYjovL21vbmdvLTAubW9uZ28uZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNyxtb25nby0xLm1vbmdvLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcsbW9uZ28tMi5tb25nby5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3Lz9yZXBsaWNhU2V0PXJzMA==
metadata:
  creationTimestamp: null
  name: mongo-creds
type: Opaque
