apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: master-decision
  name: master-decision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-decision
  template:
    metadata:
      labels:
        app: master-decision
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - image: yxchia98/master-decision-node
          name: master-decision
          env:
            - name: GRPC_SERVER_URL
              value: queue-server-nodeport-service.default.svc.cluster.local:50051
            - name: FINAL_PAGE_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: master-decision-configmap
                  key: final_website_url