apiVersion: v1
kind: Service
metadata:
  labels:
    app: master-decision
  name: master-decision-nodeport-service
spec:
  type: NodePort
  selector:
    app: master-decision
  ports:
    - port: 12345
      protocol: TCP
      targetPort: 12345
      nodePort: 32015
